// src/components/admin/RevenueByService.jsx

import {
    ResponsiveContainer,
    BarChart,
    Bar,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip
} from "recharts";

function RevenueByService({ data = [] }) {

    return (
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">

            <div className="mb-6">
                <h2 className="text-lg font-bold text-slate-900">
                    Revenue by Service
                </h2>

                <p className="text-sm text-slate-500 mt-1">
                    Revenue generated by service category
                </p>
            </div>

            <div className="h-[320px]">

                {data.length === 0 ? (

                    <div className="h-full flex items-center justify-center text-sm text-slate-400">
                        No service revenue data available
                    </div>

                ) : (

                    <ResponsiveContainer width="100%" height="100%">

                        <BarChart
                            data={data}
                            margin={{
                                top: 10,
                                right: 20,
                                left: 10,
                                bottom: 10
                            }}
                        >

                            <CartesianGrid
                                strokeDasharray="3 3"
                                vertical={false}
                            />

                            <XAxis
                                dataKey="service"
                                tick={{
                                    fontSize: 12
                                }}
                            />

                            <YAxis
                                tick={{
                                    fontSize: 12
                                }}
                            />

                            <Tooltip
                                formatter={(value) =>
                                    `₹${Number(value).toLocaleString("en-IN")}`
                                }
                            />

                            <Bar
                                dataKey="revenue"
                                name="Revenue"
                                radius={[6, 6, 0, 0]}
                            />

                        </BarChart>

                    </ResponsiveContainer>

                )}

            </div>

        </div>
    );
}

export default RevenueByService;